package: structure_tweaks
version: '2.0.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/structure_tweaks

page:
    title: 'translate:structure_tweaks'
    perm: admin
    pjax: true
    icon: rex-icon rex-icon-package
    subpages:
        categories: { title: 'translate:page_categories' }
        help: { title: 'translate:help', subPath: README.md, itemClass: 'pull-right' }

requires:
    php: '>=8.4'
    redaxo: '^5.20.0'
    packages:
        structure: '^2.2.0'


