package: structure_tweaks
version: '1.3.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/structure_tweaks

requires:
    php: '>=7.3'
    redaxo: '^5.2.0'
    packages:
        structure: '^2.2.0'

page:
    title: translate:structure_tweaks
    perm: admin
    subpages:
        categories: { title: translate:page_categories }
        info:
          title: translate:page_info
          itemclass: pull-right


