package: structure_tweaks
version: '1.0.0-beta4'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO

requires:
    redaxo: '^5.2.0'
    packages:
        structure: '^2.2.0'

page:
    title: translate:structure_tweaks
    perm: admin
    subpages:
        categories: { title: translate:page_categories }
        settings: { title: translate:page_settings }
        info: { title: translate:page_info }
